### ISSUE TITLE
手动运行可以成功，自动运行登录失败

### ISSUE THREAD

**Issue by IskandarZhang** [blueice-thu/gkd-auto-report#1]
已经连续三天这样了，自动运行会收到推送称登录失败。

我能想到的改动是疫苗第三针处从未接种改为了已接种，请问这种情况应该怎么解决？

**Comment by LCDGITH** [comment]
与这个改动无关，我最早十几天前大概，就已经改了，一直运行的很好。而且登录在填信息前。
我也是无法自动运行了，一直提醒登录失败。
希望大佬修改解决！！

**Comment by yorhaha** [comment]
奇怪，我的 Actions 一直是正常的，而且没有复现这个问题

![image](https://user-images.githubusercontent.com/42489990/192202769-b0c06568-f5e3-42b0-b706-f7a761edcd42.png)

要不你们重新 fork 试试？如果还是有问题的话，我就在登录部分加上错误重试和多次打卡检查功能。

**Comment by LCDGITH** [comment]
![image](https://user-images.githubusercontent.com/100296035/192204838-70c92855-7e96-48c8-8a6d-fe4ca9cde86c.png)
![image](https://user-images.githubusercontent.com/100296035/192204882-c1d26aa9-bcd8-474c-ba0c-9b7c43ae9273.png)
这是错误情况，好的，我重新fork试试

**Comment by IskandarZhang** [comment]
> 奇怪，我的 Actions 一直是正常的，而且没有复现这个问题
> 
> ![image](https://user-images.githubusercontent.com/42489990/192202769-b0c06568-f5e3-42b0-b706-f7a761edcd42.png)
> 
> 要不你们重新 fork 试试？如果还是有问题的话，我就在登录部分加上错误重试和多次打卡检查功能。

![image](https://user-images.githubusercontent.com/57842153/192277446-45c4fac9-2564-4c56-8a0d-1e0df3e8bfd6.png)
你好 我注意到main.py中对应的是`GKD_EMAIL`等变量名而不是`EMAIL`等名，是否创立secrets时也需要在变量前加`GKD_`？因为重新fork之后手动运行workflow还是会报同样的错误

**Comment by LCDGITH** [comment]
不对，GKD_EMAIL等变量名而不是EMAIL等名是正确的。

**Comment by yorhaha** [comment]
> 不对，GKD_EMAIL等变量名而不是EMAIL等名是正确的。

你看下这几行代码，这里对 secrets 等环境变量进行了重新命名：

https://github.com/blueice-thu/gkd-auto-report/blob/89192e1aca7cba030da082b88c7adf1602f853d1/.github/workflows/report.yml#L27

这样做是考虑到 secrets 里面的命名尽量易懂，而代码里面为了标识环境变量统一加了前缀 `GKD` 。

**Comment by LCDGITH** [comment]
是的，所以我说这是正确的，问题不在这里。：）

**Comment by yorhaha** [comment]
> 是的，所以我说这是正确的，问题不在这里。：）

我看你的 Actions 记录已经运行成功了

**Comment by IskandarZhang** [comment]
> > 是的，所以我说这是正确的，问题不在这里。：）
> 
> 我看你的 Actions 记录已经运行成功了

是的 我只看到了运行失败 但是没注意详细原因是因为已手动填报过了 今天凌晨再看一下能否自动填报

**Comment by yorhaha** [comment]
我这儿复现了，今天看下什么原因

**Comment by yorhaha** [comment]
问题基本已经确定了，凌晨 0 - 1 点之间系统登录不上去，换到一点之后的时间就 OK 了

**Comment by LCDGITH** [comment]
哇，这下明白了，这就去改一改自动运行的时间
